version: "3.8"
services:
  backend:
    build:
      context: ./erp-crm-backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    command: ["npm", "run", "start:dev"]
    ports:
      - "5000:3000"
    restart: unless-stopped
