version: "3.8"
services:
  backend:
    build:
      context: ./erp-crm-backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    command: ["npm", "run", "start:production"]
    ports:
      - "5002:3000"
    restart: unless-stopped
