version: "3.8"
services:
  backend:
    build:
      context: ./erp-crm-backend
      dockerfile: Dockerfile
    ports:
      - "5000:3000"

  # frontend:
  #   build:
  #     context: ./erp-crm-frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5001:3001"
