version: "3.8"
services:
  backend:
    build:
      context: ./erp-crm-backend
      dockerfile: Dockerfile
      target: production
    ports:
      - "5002:3000"
    env_file:
      - ./erp-crm-backend/.env.production
