version: "3.8"
services:
  backend:
    build:
      context: ./erp-crm-backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: staging
    command: ["npm", "run", "start:staging"]
    ports:
      - "5001:3000"
    restart: unless-stopped
