name: Deploy to VPS

on:
  push:
    branches:
      - master # Production
      - staging # Staging
      - development # Development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t trkfabi/erp-crm-app:${{ github.ref_name }} -f ./erp-crm-backend/Dockerfile ./erp-crm-backend
          docker push trkfabi/erp-crm-app:${{ github.ref_name }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@145.223.120.220 << 'EOF'
            cd /srv/node/ErpCrm
            docker-compose -f docker-compose.${{ github.ref_name }}.yml down
            docker-compose -f docker-compose.${{ github.ref_name }}.yml up -d --build
          EOF
