name: Deploy to VPS

on:
  push:
    branches:
      - master # O la rama que desees monitorear

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@145.223.120.220 << 'EOF'
            cd /srv/node/ErpCrm
            git pull origin master

            # Enable BuildKit
              export DOCKER_BUILDKIT=1
              docker buildx create --use

            # use docker-compose
            docker-compose down
            docker-compose up -d --build



            # Backend
            #cd erp-crm-backend
            #docker stop erpcrm-backend-container || true
            #docker rm erpcrm-backend-container || true
            #docker build -t erpcrm-backend-app -f Dockerfile .
            #docker run -d -p 5000:3000 --name erpcrm-backend-container erpcrm-backend-app

            # Frontend
            #cd ../erp-crm-frontend
            #docker stop erpcrm-frontend-container || true
            #docker rm erpcrm-frontend-container || true
            #docker build -t erpcrm-frontend-app -f Dockerfile .
            #docker run -d -p 5001:3001 --name erpcrm-frontend-container erpcrm-frontend-app
          EOF
